apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
        - configmap.yaml
        - elastic-search.yaml
        - logstash.yaml
        - kibana.yaml
        - filebeat.yaml
